# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LiveMeasureClass
                                 A QGIS plugin
 Affiche en temps réel les distances, surfaces et autres mesures directement sur la carte pendant la numérisation d'entités.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-03
        copyright            : (C) 2025 by Amr HAMADEH
        email                : amr.grenoble@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LiveMeasureClass class from file LiveMeasureClass.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Live_Measure import LiveMeasureClass
    return LiveMeasureClass(iface)
